# Generated by Django 4.1.1 on 2022-09-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goods_name', models.CharField(max_length=127)),
                ('receiver_address', models.TextField(max_length=1023)),
                ('total_value', models.FloatField()),
                ('state', models.CharField(choices=[('CREATED', 'Created'), ('READY', 'Ready'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received'), ('UNSUCCESSFUL', 'Unsuccessful')], default='CREATED', max_length=15)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
